import os


oeg = os.environ.get

MONGO_DB_NAME = oeg('SPY_BOY_MONGO_DB_NAME', 'test-spy-boy')
MONGO_USERNAME = oeg('SPY_BOY_MONGO_USERNAME', '')
MONGO_PASSWORD = oeg('SPY_BOY_MONGO_PASSWORD', '')

DISCORD_TOKEN = oeg('SPY_BOY_DISCORD_TOKEN', '')

CLEANING_REFRESH_TIME = oeg('SPY_BOY_CLEANING_REFRESH_TIME', 300)
